<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-31T09:59:56 IST" name="Default suite" finished-at="2024-05-31T10:00:11 IST" duration-ms="15208">
    <groups>
    </groups>
    <test started-at="2024-05-31T09:59:56 IST" name="Default test" finished-at="2024-05-31T10:00:11 IST" duration-ms="15208">
      <class name="extentreport.CaptureScreenShotWithExtentReport">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:extentreport.CaptureScreenShotWithExtentReport@8458f04]" started-at="2024-05-31T09:59:56 IST" name="beforeClass" finished-at="2024-05-31T09:59:59 IST" duration-ms="3164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:extentreport.CaptureScreenShotWithExtentReport@8458f04]" started-at="2024-05-31T09:59:59 IST" name="beforeMethod" finished-at="2024-05-31T09:59:59 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="dwsLoginWrong()[pri:0, instance:extentreport.CaptureScreenShotWithExtentReport@8458f04]" started-at="2024-05-31T09:59:59 IST" name="dwsLoginWrong" finished-at="2024-05-31T10:00:06 IST" duration-ms="6632" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [142] but found [123]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [142] but found [123]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at extentreport.CaptureScreenShotWithExtentReport.dwsLoginWrong(CaptureScreenShotWithExtentReport.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dwsLoginWrong -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:extentreport.CaptureScreenShotWithExtentReport@8458f04]" started-at="2024-05-31T10:00:06 IST" name="afterMethod" finished-at="2024-05-31T10:00:06 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:extentreport.CaptureScreenShotWithExtentReport@8458f04]" started-at="2024-05-31T10:00:06 IST" name="beforeMethod" finished-at="2024-05-31T10:00:06 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="dwsLoginCorrect()[pri:0, instance:extentreport.CaptureScreenShotWithExtentReport@8458f04]" started-at="2024-05-31T10:00:06 IST" name="dwsLoginCorrect" finished-at="2024-05-31T10:00:10 IST" duration-ms="4402" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dwsLoginCorrect -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:extentreport.CaptureScreenShotWithExtentReport@8458f04]" started-at="2024-05-31T10:00:10 IST" name="afterMethod" finished-at="2024-05-31T10:00:10 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="redBus()[pri:0, instance:extentreport.CaptureScreenShotWithExtentReport@8458f04]" started-at="2024-05-31T10:00:10 IST" name="redBus" finished-at="2024-05-31T10:00:10 IST" depends-on-methods="extentreport.CaptureScreenShotWithExtentReport.dwsLoginWrong" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method extentreport.CaptureScreenShotWithExtentReport.redBus() on instance extentreport.CaptureScreenShotWithExtentReport@8458f04 depends on not successfully finished methods 
[extentreport.CaptureScreenShotWithExtentReport.dwsLoginWrong() on instance extentreport.CaptureScreenShotWithExtentReport@8458f04]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method extentreport.CaptureScreenShotWithExtentReport.redBus() on instance extentreport.CaptureScreenShotWithExtentReport@8458f04 depends on not successfully finished methods 
[extentreport.CaptureScreenShotWithExtentReport.dwsLoginWrong() on instance extentreport.CaptureScreenShotWithExtentReport@8458f04]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- redBus -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:extentreport.CaptureScreenShotWithExtentReport@8458f04]" started-at="2024-05-31T10:00:10 IST" name="afterClass" finished-at="2024-05-31T10:00:11 IST" duration-ms="443" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- extentreport.CaptureScreenShotWithExtentReport -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
